import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/hook/Providers";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Matrix",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" className="dark">
         <body className={inter.className}>
            <ToastContainer
               position="top-right"
               autoClose={5000}
               hideProgressBar={true}
               newestOnTop={false}
               closeOnClick
               rtl={false}
               draggable
               theme="dark"
            />
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
